### ISSUE TITLE
Single document updating

### ISSUE THREAD

**Issue by ilevennet** [kvz/cakephp-elasticsearch-plugin#8]
I've installed your plugin.
Bulk insert with shell script is ok, but a single record(document) update generate this (i've added echo() to error):

``` php
Array
(
    [error] => ActionRequestValidationException[Validation Failed: 1: no requests added;]
    [status] => 500
)
Array
(
    [error] => ElasticSearchParseException[Failed to derive xcontent from (offset=0, length=0): []]
    [status] => 400
)
```

and it was not saved/modified

**Comment by clns** [comment]
Any update on this?
@ciccimanolesta did you fix it? If so, can you make a pull request or share the fix?

**Comment by ilevennet** [comment]
no @calin-s, no updates for now.

**Comment by jubaleth** [comment]
See https://github.com/kvz/cakephp-elasticsearch-plugin/pull/9 for the fix

**Comment by kvz** [comment]
Mergin the PR. Not actively maintaining this so thanks for helping out guys
